[project]
name = "drl-trading-impl-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "drl-trading-common",
]

[tool.uv.sources]
drl-trading-common = { path = "../drl-trading-common" }
