[project]
name = "drl-trading-impl-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "drl-trading-framework",
]

[tool.uv.sources]
drl-trading-framework = { path = "../drl-trading-framework" }
